Force CI integration tests to run locally.

diff --git a/.github/workflows/ansible-test.yml b/.github/workflows/ansible-test.yml
--- a/.github/workflows/ansible-test.yml
+++ b/.github/workflows/ansible-test.yml
@@ -58,6 +58,30 @@ jobs:
         terraform:
           - "1.3.4"
     steps:
+      # we want to force tests to run locally, not in docker, so we replace --docker with --local forcefully
+      # a bit of a hack but what can you do
+      - name: Provision the ansible-test arg filtering script
+        run: |
+          mkdir -p ~/.local/bin/
+          cat >~/.local/bin/ansible-test-filtered <<EOF
+          #!/bin/sh
+          set -eux
+          args="\$(echo "\$*" | sed "s/--docker/--local/")"
+          exec ~/.local/bin/ansible-test-actual \$args
+          EOF
+          
+          chmod +x ~/.local/bin/ansible-test-filtered
+          cat ~/.local/bin/ansible-test-filtered
+        shell: bash
+
+      # we use raw git to create a repository in the tests
+      # this fails if the committer doesn't have a name and an email set
+      - name: Set up git
+        run: |
+          git config --global user.email gha@localhost
+          git config --global user.name "Github Actions"
+        shell: bash
+
       - name: >-
           Perform integration testing against
           Ansible version ${{ matrix.ansible }}
@@ -66,10 +90,16 @@ jobs:
         uses: ansible-community/ansible-test-gh-action@release/v1
         with:
           ansible-core-version: ${{ matrix.ansible }}
+          origin-python-version: ${{ matrix.python }}
           target-python-version: ${{ matrix.python }}
           testing-type: integration
           target: --exclude gcp --exclude aws --exclude azure
           pre-test-cmd: |-
+            pip install coverage
+            
             curl -L https://releases.hashicorp.com/terraform/${{ matrix.terraform }}/terraform_${{ matrix.terraform }}_linux_amd64.zip | zcat > terraform
             chmod +x terraform
             sudo mv terraform /usr/bin/terraform
+
+            mv ~/.local/bin/ansible-test ~/.local/bin/ansible-test-actual
+            mv ~/.local/bin/ansible-test-filtered ~/.local/bin/ansible-test
